// Next
import { Inter, Poppins } from 'next/font/google';
import type { Metadata } from 'next';

// Styles
import './globals.css';

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '500', '700'] });

export const metadata: Metadata = {
	title: 'Cleibson | Front End Developer',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: { locale: string };
}>) {
	return (
		<html lang={params.locale ?? 'pt'}>
			<body className={poppins.className} suppressHydrationWarning={true}>
				{children}
			</body>
		</html>
	);
}
