// Next
import { Poppins } from 'next/font/google';
import type { Metadata } from 'next';

// Styles
import './globals.css';

// Components
import Header from '@/components/global/Header';

export const poppins = Poppins({
	subsets: ['latin'],
	weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
	title: 'Cleibson | Front End Developer',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: { locale: string };
}>) {
	return (
		<html lang={params.locale ?? 'pt'}>
			<body
				className={`${poppins.className} bg-background h-[2000px]`}
				suppressHydrationWarning={true}
			>
				<Header params={params} />
				{children}
			</body>
		</html>
	);
}
