// Next
import { Poppins } from 'next/font/google';
import type { Metadata } from 'next';

// Styles
import './globals.css';

// Components
import Header from '@/components/global/Header';

// Contexts
import { CursorProvider } from '@/contexts/MouseContext';
import TranslationsProvider from '@/contexts/TranslationProvider';
import initTranslations from '@/i18n';

export const poppins = Poppins({
	subsets: ['latin'],
	weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
	title: 'Cleibson | Front End Developer',
	description: 'Generated by create next app',
};

const i18nNamespaces = ['home', 'common'];

export default async function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: { locale: string };
}>) {
	const { t, resources } = await initTranslations(
		params.locale,
		i18nNamespaces
	);

	return (
		<html lang={params.locale ?? 'pt'}>
			<body
				className={`${poppins.className} bg-background h-[4000px]`}
				suppressHydrationWarning={true}
			>
				<TranslationsProvider
					resources={resources}
					locale={params.locale}
					namespaces={['home']}
				>
					<CursorProvider>
						<Header params={params} />
						{children}
					</CursorProvider>
				</TranslationsProvider>
			</body>
		</html>
	);
}
